In [1]:
import torch

In [3]:
a = [[11,12,13],[21,22,23],[31,32,33]]

In [6]:
b = torch.tensor(a)
b

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [8]:
b.ndimension()

2

In [9]:
b.shape

torch.Size([3, 3])

In [10]:
b.size()

torch.Size([3, 3])

In [11]:
b.numel()

9

In [12]:
b

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [13]:
b[1]

tensor([21, 22, 23])

In [16]:
b[1,1]

tensor(22)

In [18]:
b[1][1]

tensor(22)

In [21]:
b[1,0:2]

tensor([21, 22])

In [22]:
b[1:3,1]

tensor([22, 32])

In [23]:
b[1:3,0:1]

tensor([[21],
        [31]])

In [24]:
x = torch.tensor([[1,0],[1,1]])
y = torch.tensor([[2,1],[1,3]])
x+y

tensor([[3, 1],
        [2, 4]])

In [30]:
2*y

tensor([[4, 2],
        [2, 6]])

In [31]:
x*y

tensor([[2, 0],
        [1, 3]])

In [34]:
a = torch.tensor([[1,2,2],[2,3,1]])
b = torch.tensor([[3,2],[6,3],[4,2]])
print(a)
print(b)

tensor([[1, 2, 2],
        [2, 3, 1]])
tensor([[3, 2],
        [6, 3],
        [4, 2]])


In [36]:
torch.mm(a,b)     # matrix multiplication

tensor([[23, 12],
        [28, 15]])

In [37]:
import numpy as np 
import pandas as pd

In [39]:
a = [[11,12,13],[21,22,23],[31,32,33]]

In [40]:
twoD_tensor = torch.tensor(a)
twoD_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [44]:
twoD_numpy = twoD_tensor.numpy()
print("Tensor -> Numpy Array:")
print("The numpy array after converting:  \n", twoD_numpy)
print("Type after converting: ", twoD_numpy.dtype)

Tensor -> Numpy Array:
The numpy array after converting:  
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Type after converting:  int64


In [45]:
new_twoD_tensor = torch.from_numpy(twoD_numpy)
print("Numpy Array -> Tensor:")
print("The tensor after converting: \n", new_twoD_tensor)
print("Type after converting: ", new_twoD_tensor.dtype)

Numpy Array -> Tensor:
The tensor after converting: 
 tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Type after converting:  torch.int64


In [48]:
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})

print("Pandas Dataframe to numpy: \n", df.values)
print("Type BEFORE converting: ", df.values.dtype)

Pandas Dataframe to numpy: 
 [[ 11  12]
 [ 21  22]
 [ 31 312]]
Type BEFORE converting:  int64


In [49]:
new_tensor = torch.from_numpy(df.values)
print("Tensor AFTER converting: \n", new_tensor)
print("Type AFTER converting: ", new_tensor.dtype)

Tensor AFTER converting: 
 tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
Type AFTER converting:  torch.int64


In [71]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})

converted_tensor = torch.tensor(df.values)
converted_tensor

tensor([[11,  3],
        [33,  3],
        [22,  2]])

In [73]:
# Practice: Use slice and index to change the values on the matrix tensor_ques.

tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

tensor_ques[1:3, 1] = 0
tensor_ques

tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])